elasticmq:
  image: softwaremill/elasticmq
  ports:
    - 9324:9324    
elasticsearch:
  build: ./docker/elasticsearch
  ports:
    - 9200:9200
    - 9300:9300
go:
  build: ./docker/go
  volumes:
    - ./src:/go/src        
  tty: true

